print("=" * 50)
print("🧪 STOCK SENTIMENT ANALYZER - TEST VERSION")
print("=" * 50)
print("")
print("✅ Python is working correctly!")
print("📅 Current time:", __import__("datetime").datetime.now())
print("📁 File location:", __file__)
print("")
print("🎉 CONGRATULATIONS!")
print("You successfully ran a Python script!")
print("")
print("Next steps:")
print("1. Get Twitter API keys from developer.twitter.com")
print("2. Add them to .env file")
print("3. Run the full version")
print("=" * 50)
